##Final Lab:Construct a QA Bot That Leverages the LangChain and LLM to Answer Questions from Loaded Documents.##
#Install necessary libraries here: 
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA
#Import here:
import gradio as gr

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
#model_id = 'mistralai/mixtral-8x7b-instruct-v01' # Specify the Mixtral 8x7B model
##mixtralai model not supported in this environment.
## LLM:
def get_llm():
    model_id = 'ibm/granite-3-2-8b-instruct'
    parameters = {
         GenParams.MAX_NEW_TOKENS: 256,  # this controls the maximum number of tokens in the generated output
        GenParams.TEMPERATURE: 0.5, # this randomness or creativity of the model's responses,
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id= model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id= project_id,
        params=parameters,
    )
    return watsonx_llm

##Task 1: Load document using LangChain for different sources:##
## Document loader:
def document_loader(file):
    loader = PyPDFLoader(file.name)
    loaded_document = loader.load()
    return loaded_document

##Task 2: Apply text splitting techniques:##
## Text splitter:
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=20,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks

##Task 3: Embed documents:##
## Embedding model:
def watsonx_embedding():
    embed_params = {
    EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3,
    EmbedTextParamsMetaNames.RETURN_OPTIONS: {"input_text": True}
    }
    watsonx_embedding = WatsonxEmbeddings(
        model_id="ibm/slate-125m-english-rtrvr",
        url="https://us-south.ml.cloud.ibm.com",
        project_id="skills-network",
        params=embed_params,
    )
    return watsonx_embedding

##check embedding display first five numbers:##
#query_chk = "How are you?"
#query_chk_result = watsonx_embedding().embed_query(query_chk)
#print(f"Embed dimension length: {len(query_chk_result)}. It should be 768. Yes it is!\n")
#print(f"Embedding first 5 numbers: {query_chk_result[:5]}")
##End of check embedding portion.##

##Task 4: Create and configure vector databases to store embeddings:##
## Vector db:
def vector_database(chunks):
    embedding_model = watsonx_embedding()
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb

##Task 5: Develop a retriever to fetch document segments based on queries:##
## Retriever:
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever(search_type = 'similarity') # simple similarity search.
    return retriever

##Task 6: Construct a QA Bot that leverages the LangChain and LLM to answer questions:##
## QA Chain:
def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_obj, 
                                    return_source_documents=True)
    response = qa.invoke(query)
    return response['result']

##Integrating the Gradio Interface for the QA Bot:##
# Create Gradio interface:
rag_application = gr.Interface(
    fn= retriever_qa,
    allow_flagging="never",
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query:", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output Response:"),
    title= "QA() CHATBOT: ",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

##Launch the Gradio App:##
rag_application.launch(server_name="127.0.0.1", server_port= 7860)